export const dummyMembers = [
    { id: 'd001', full_name: 'Dr. Aminata Diop', country: 'Senegal, Touba', profession: 'Educator', year_connected: 2019, first_encounter: 'Introduced through a community learning circle in Touba.', resonated_quality: 'Clarity', life_changes: 'Developed a more reflective and values-based approach to education.', continuing_engagement: 'Participating in educational and youth-oriented initiatives connected to Touba.' },
    { id: 'd002', full_name: 'Moussa Ndiaye', country: 'Senegal, Kaolack', profession: 'Civil Servant', year_connected: 2020, first_encounter: 'Connected through a governance and service forum in Kaolack.', resonated_quality: 'Ethical_Conduct', life_changes: 'Renewed commitment to public ethics and accountable service.', continuing_engagement: 'Supporting civic and institutional dialogue initiatives in Kaolack.' },
  
    { id: 'd003', full_name: 'Zoya Chishti', country: 'India, Ajmer', profession: 'Writer', year_connected: 2021, first_encounter: 'Introduced through a literary and spiritual gathering in Ajmer.', resonated_quality: 'Reflective_Silence', life_changes: 'Brought greater contemplative depth into writing and documentation.', continuing_engagement: 'Contributing to reflective writing circles and cultural initiatives in Ajmer.' },
    { id: 'd004', full_name: 'Arman Qadri', country: 'India, Delhi', profession: 'Journalist', year_connected: 2020, first_encounter: 'Discovered the Foundation through an ethics and media dialogue in Delhi.', resonated_quality: 'Clarity', life_changes: 'Developed a more grounded and ethically conscious approach to storytelling.', continuing_engagement: 'Supporting communications and public dialogue efforts linked to Delhi.' },
    { id: 'd005', full_name: 'Dr. Shazia Bhat', country: 'India, Srinagar', profession: 'Environmental Scientist', year_connected: 2022, first_encounter: 'Connected through stewardship and ecological reflection sessions in Srinagar.', resonated_quality: 'Shared_Responsibility', life_changes: 'Integrated ethical and ecological awareness more deeply into professional work.', continuing_engagement: 'Contributing to environmental and community reflection initiatives in Srinagar.' },
    { id: 'd006', full_name: 'Imran Wani', country: 'India, Ganderbal', profession: 'Student', year_connected: 2023, first_encounter: 'Introduced through a youth mentorship circle in Ganderbal.', resonated_quality: 'Self_Awareness', life_changes: 'Gained greater discipline and personal direction in academic life.', continuing_engagement: 'Participating in youth learning circles and community service activities in Ganderbal.' },
    { id: 'd007', full_name: 'Rukhsana Mir', country: 'India, Budgam', profession: 'Social Worker', year_connected: 2021, first_encounter: 'Connected through grassroots community development work in Budgam.', resonated_quality: 'Compassion', life_changes: 'Strengthened commitment to community-centered and healing-oriented service.', continuing_engagement: 'Leading support and outreach initiatives in Budgam.' },
  
    { id: 'd008', full_name: 'Dr. Mahnoor Ali', country: 'Pakistan, Lahore', profession: 'Doctor', year_connected: 2018, first_encounter: 'Attended a healing and ethics discussion in Lahore.', resonated_quality: 'Compassion', life_changes: 'Integrated compassionate care more intentionally into medical practice.', continuing_engagement: 'Supporting healing and community health initiatives linked to Lahore.' },
    { id: 'd009', full_name: 'Eng. Hamza Qureshi', country: 'Pakistan, Multan', profession: 'Engineer', year_connected: 2019, first_encounter: 'Introduced through a professional values forum in Multan.', resonated_quality: 'Discipline', life_changes: 'Became more intentional and service-oriented in technical work.', continuing_engagement: 'Contributing to infrastructure and youth mentorship efforts in Multan.' },
    { id: 'd010', full_name: 'Prof. Areeba Farid', country: 'Pakistan, Pakpattan', profession: 'Professor', year_connected: 2020, first_encounter: 'Connected through an academic gathering in Pakpattan.', resonated_quality: 'Inner_Discipline', life_changes: 'Integrated contemplative depth into teaching and mentorship.', continuing_engagement: 'Facilitating educational and dialogue-based initiatives linked to Pakpattan.' },
    { id: 'd011', full_name: 'Salman Raza', country: 'Pakistan, Sehwan Sharif', profession: 'Artist', year_connected: 2022, first_encounter: 'Discovered the Foundation through a cultural exchange event in Sehwan Sharif.', resonated_quality: 'Reflective_Silence', life_changes: 'Developed a stronger spiritual and ethical foundation in creative work.', continuing_engagement: 'Participating in cultural documentation and community arts initiatives in Sehwan Sharif.' },
  
    { id: 'd012', full_name: 'Ar. Elif Demir', country: 'Turkey, Konya', profession: 'Architect', year_connected: 2019, first_encounter: 'Introduced through a design and sacred space dialogue in Konya.', resonated_quality: 'Discipline', life_changes: 'Adopted a more mindful and humane approach to architectural practice.', continuing_engagement: 'Supporting design-related and cultural exchange initiatives connected to Konya.' },
    { id: 'd013', full_name: 'Mehmet Yildiz', country: 'Turkey, Istanbul', profession: 'Entrepreneur', year_connected: 2021, first_encounter: 'Connected through a values-based leadership circle in Istanbul.', resonated_quality: 'Accountability', life_changes: 'Shifted business leadership toward ethics, reflection, and service.', continuing_engagement: 'Supporting entrepreneurship and community-oriented initiatives in Istanbul.' },
  
    { id: 'd014', full_name: 'Prof. Nusrat Jahan', country: 'Bangladesh, Sylhet', profession: 'Professor', year_connected: 2020, first_encounter: 'Attended an educational and spiritual dialogue in Sylhet.', resonated_quality: 'Clarity', life_changes: 'Brought greater moral and reflective depth into teaching and scholarship.', continuing_engagement: 'Facilitating educational and dialogue-based activities in Sylhet.' },
  
    { id: 'd015', full_name: 'Youssef El Idrissi', country: 'Morocco, Fez', profession: 'Designer', year_connected: 2018, first_encounter: 'Connected through a cultural and design exchange in Fez.', resonated_quality: 'Self_Awareness', life_changes: 'Developed a more meaningful and values-driven creative practice.', continuing_engagement: 'Contributing to design and heritage documentation initiatives linked to Fez.' },
  
    { id: 'd016', full_name: 'Zainab Al-Hadithi', country: 'Iraq, Baghdad', profession: 'Policy Analyst', year_connected: 2021, first_encounter: 'Introduced through a governance and ethics discussion in Baghdad.', resonated_quality: 'Ethical_Conduct', life_changes: 'Strengthened commitment to justice-oriented and principled policy work.', continuing_engagement: 'Supporting policy reflection and civic dialogue initiatives in Baghdad.' },
  
    { id: 'd017', full_name: 'Dr. Dilshod Karimov', country: 'Uzbekistan, Bukhara', profession: 'Researcher', year_connected: 2020, first_encounter: 'Connected through a historical and intellectual forum in Bukhara.', resonated_quality: 'Clarity', life_changes: 'Deepened research through a more reflective and values-centered lens.', continuing_engagement: 'Contributing to research and archival initiatives in Bukhara.' },
    { id: 'd018', full_name: 'Amb. Madina Rakhimova', country: 'Uzbekistan, Samarkand', profession: 'Diplomat', year_connected: 2022, first_encounter: 'Introduced through an intercultural dialogue circle in Samarkand.', resonated_quality: 'Shared_Responsibility', life_changes: 'Developed a more humane and bridge-building approach to diplomacy.', continuing_engagement: 'Participating in cultural dialogue and international engagement efforts linked to Samarkand.' },
  
    { id: 'd019', full_name: 'Dr. Aigerim Saparova', country: 'Kazakhstan, Turkestan', profession: 'Scientist', year_connected: 2021, first_encounter: 'Connected through a science and ethics forum in Turkestan.', resonated_quality: 'Self_Awareness', life_changes: 'Brought greater reflection and responsibility into scientific work.', continuing_engagement: 'Supporting research dialogue and youth learning activities in Turkestan.' },
  
    { id: 'd020', full_name: 'Hon. Abdoulaye Traore', country: 'Mali, Timbuktu', profession: 'Legislator', year_connected: 2019, first_encounter: 'Introduced through a civic leadership exchange in Timbuktu.', resonated_quality: 'Accountability', life_changes: 'Renewed commitment to public duty guided by ethics and service.', continuing_engagement: 'Supporting governance and public dialogue initiatives connected to Timbuktu.' },
  
    { id: 'd021', full_name: 'Sarah Johnson', country: 'United States, New York City', profession: 'Banker', year_connected: 2020, first_encounter: 'Connected through a finance and ethics discussion in New York City.', resonated_quality: 'Accountability', life_changes: 'Shifted toward a more responsible and values-based professional outlook.', continuing_engagement: 'Participating in ethical leadership and mentorship initiatives in New York City.' },
    { id: 'd022', full_name: 'Daniel Martinez', country: 'United States, Los Angeles', profession: 'Technologist', year_connected: 2021, first_encounter: 'Introduced through a digital ethics and innovation circle in Los Angeles.', resonated_quality: 'Clarity', life_changes: 'Developed greater intentionality in the use of technology and design.', continuing_engagement: 'Supporting digital literacy and youth-focused initiatives in Los Angeles.' },
    { id: 'd023', full_name: 'Amina Rahman', country: 'United States, San Francisco', profession: 'Business Leader', year_connected: 2022, first_encounter: 'Connected through a leadership and reflection forum in San Francisco.', resonated_quality: 'Self_Awareness', life_changes: 'Reshaped leadership style toward service, humility, and responsibility.', continuing_engagement: 'Supporting leadership and entrepreneurship initiatives linked to San Francisco.' },
    { id: 'd024', full_name: 'Dr. James Walker', country: 'United States, Dallas', profession: 'Public Health Expert', year_connected: 2019, first_encounter: 'Introduced through a community health dialogue in Dallas.', resonated_quality: 'Compassion', life_changes: 'Integrated human-centered care more fully into public health practice.', continuing_engagement: 'Participating in health awareness and outreach efforts in Dallas.' },
    { id: 'd025', full_name: 'Dr. Sophia Turner', country: 'United States, Houston', profession: 'Medical Specialist', year_connected: 2023, first_encounter: 'Connected through a healing and resilience session in Houston.', resonated_quality: 'Compassion', life_changes: 'Brought greater empathy and reflection into specialist care.', continuing_engagement: 'Supporting health and healing initiatives in Houston.' },
    { id: 'd026', full_name: 'Adv. Michael Harris', country: 'United States, Chicago', profession: 'Lawyer', year_connected: 2020, first_encounter: 'Introduced through a justice and ethics forum in Chicago.', resonated_quality: 'Ethical_Conduct', life_changes: 'Renewed commitment to principled advocacy and ethical legal work.', continuing_engagement: 'Supporting legal literacy and civic dialogue initiatives in Chicago.' },
  
    { id: 'd027', full_name: 'Prof. Emily Thompson', country: 'Canada, Toronto', profession: 'Professor', year_connected: 2018, first_encounter: 'Connected through an academic dialogue in Toronto.', resonated_quality: 'Inner_Discipline', life_changes: 'Integrated reflective practice more deeply into teaching and scholarship.', continuing_engagement: 'Facilitating educational and mentoring programs in Toronto.' },
    { id: 'd028', full_name: 'Ar. Olivier Gagnon', country: 'Canada, Montreal', profession: 'Architect', year_connected: 2021, first_encounter: 'Introduced through a design and community space initiative in Montreal.', resonated_quality: 'Discipline', life_changes: 'Adopted a more mindful and socially grounded design philosophy.', continuing_engagement: 'Supporting design and cultural engagement efforts in Montreal.' },
    { id: 'd029', full_name: 'Dr. Sana Malik', country: 'Canada, Vancouver', profession: 'Researcher', year_connected: 2022, first_encounter: 'Connected through a research network and dialogue circle in Vancouver.', resonated_quality: 'Reflective_Silence', life_changes: 'Developed a more thoughtful and integrative research approach.', continuing_engagement: 'Contributing to research and community knowledge initiatives in Vancouver.' },
  
    { id: 'd030', full_name: 'Amb. Aisha Rahman', country: 'United Kingdom, London', profession: 'Diplomat', year_connected: 2021, first_encounter: 'Introduced through an intercultural exchange in London.', resonated_quality: 'Shared_Responsibility', life_changes: 'Strengthened commitment to bridge-building and humane dialogue.', continuing_engagement: 'Participating in cultural diplomacy and dialogue initiatives in London.' },
    { id: 'd031', full_name: 'Eng. Thomas Reed', country: 'United Kingdom, Newcastle', profession: 'Engineer', year_connected: 2020, first_encounter: 'Connected through a professional ethics gathering in Newcastle.', resonated_quality: 'Discipline', life_changes: 'Applied greater reflection and service-mindedness to technical work.', continuing_engagement: 'Supporting youth mentoring and technical guidance initiatives in Newcastle.' },
  
    { id: 'd032', full_name: 'Claire Dubois', country: 'France, Paris', profession: 'Writer', year_connected: 2019, first_encounter: 'Discovered the Foundation through literary networks in Paris.', resonated_quality: 'Reflective_Silence', life_changes: 'Developed a more contemplative and ethically grounded writing practice.', continuing_engagement: 'Contributing to writing, documentation, and cultural dialogue initiatives in Paris.' },
    { id: 'd033', full_name: 'Karim Benali', country: 'France, Chatou', profession: 'Banker', year_connected: 2022, first_encounter: 'Introduced through a professional values discussion in Chatou.', resonated_quality: 'Accountability', life_changes: 'Became more intentional about ethics and stewardship in financial work.', continuing_engagement: 'Supporting mentoring and leadership dialogue initiatives linked to Chatou.' },
  
    { id: 'd034', full_name: 'Justice Anna Mueller', country: 'Germany, Berlin', profession: 'Judge', year_connected: 2018, first_encounter: 'Connected through a justice and ethics forum in Berlin.', resonated_quality: 'Ethical_Conduct', life_changes: 'Deepened commitment to fairness, discipline, and principled judgment.', continuing_engagement: 'Supporting legal ethics and public dialogue efforts in Berlin.' },
    { id: 'd035', full_name: 'Jonas Schneider', country: 'Germany, Cologne', profession: 'Designer', year_connected: 2020, first_encounter: 'Introduced through a creative and social design gathering in Cologne.', resonated_quality: 'Clarity', life_changes: 'Shifted toward more meaningful and socially responsive design work.', continuing_engagement: 'Contributing to community-focused design initiatives in Cologne.' },
    { id: 'd036', full_name: 'Dr. Leyla Demir', country: 'Germany, Düsseldorf', profession: 'Scientist', year_connected: 2021, first_encounter: 'Connected through a science and ethics dialogue in Düsseldorf.', resonated_quality: 'Self_Awareness', life_changes: 'Brought deeper reflection and responsibility into scientific practice.', continuing_engagement: 'Participating in research dialogue and mentorship activities in Düsseldorf.' },
    { id: 'd037', full_name: 'Hon. Markus Weber', country: 'Germany, Frankfurt', profession: 'Politician', year_connected: 2022, first_encounter: 'Introduced through a civic leadership exchange in Frankfurt.', resonated_quality: 'Shared_Responsibility', life_changes: 'Developed a more service-oriented approach to public leadership.', continuing_engagement: 'Supporting civic engagement and policy dialogue efforts in Frankfurt.' },
  
    { id: 'd038', full_name: 'Noor de Vries', country: 'Netherlands, Amsterdam', profession: 'Journalist', year_connected: 2020, first_encounter: 'Connected through a media and ethics discussion in Amsterdam.', resonated_quality: 'Clarity', life_changes: 'Adopted a more conscientious and humane storytelling approach.', continuing_engagement: 'Supporting communications and public dialogue initiatives in Amsterdam.' },
  
    { id: 'd039', full_name: 'Javier Moreno', country: 'Spain, Barcelona', profession: 'Artist', year_connected: 2021, first_encounter: 'Introduced through a cultural exchange program in Barcelona.', resonated_quality: 'Reflective_Silence', life_changes: 'Developed a deeper contemplative grounding in artistic work.', continuing_engagement: 'Participating in cultural and creative initiatives in Barcelona.' },
  
    { id: 'd040', full_name: 'Dr. Lina Andersson', country: 'Sweden, Stockholm', profession: 'Environmental Scientist', year_connected: 2022, first_encounter: 'Connected through environmental stewardship circles in Stockholm.', resonated_quality: 'Shared_Responsibility', life_changes: 'Integrated ethics and ecological responsibility more fully into scientific work.', continuing_engagement: 'Supporting environmental and educational initiatives in Stockholm.' },
    { id: 'd041', full_name: 'Dr. Erik Lindstrom', country: 'Sweden, Gothenburg', profession: 'Public Health Expert', year_connected: 2020, first_encounter: 'Introduced through a health and wellbeing dialogue in Gothenburg.', resonated_quality: 'Compassion', life_changes: 'Brought a more human-centered and reflective perspective into public health practice.', continuing_engagement: 'Participating in community wellbeing initiatives in Gothenburg.' },
  
    { id: 'd042', full_name: 'Adv. Sofie Nielsen', country: 'Denmark, Copenhagen', profession: 'Lawyer', year_connected: 2021, first_encounter: 'Connected through a professional ethics circle in Copenhagen.', resonated_quality: 'Ethical_Conduct', life_changes: 'Renewed commitment to justice, dignity, and principled advocacy.', continuing_engagement: 'Supporting legal awareness and community dialogue efforts in Copenhagen.' },
  
    { id: 'd043', full_name: 'Lukas Meier', country: 'Switzerland, Zurich', profession: 'Technologist', year_connected: 2019, first_encounter: 'Introduced through a technology and ethics gathering in Zurich.', resonated_quality: 'Self_Awareness', life_changes: 'Became more intentional about responsible innovation and digital impact.', continuing_engagement: 'Contributing to digital ethics and learning initiatives in Zurich.' },
  
    { id: 'd044', full_name: 'Prof. Giulia Romano', country: 'Italy, Rome', profession: 'Professor', year_connected: 2020, first_encounter: 'Connected through an academic and cultural dialogue in Rome.', resonated_quality: 'Inner_Discipline', life_changes: 'Deepened contemplative practice within teaching and scholarship.', continuing_engagement: 'Facilitating educational and cultural exchange activities in Rome.' },
  
    { id: 'd045', full_name: 'Hannah Wilson', country: 'Australia, Sydney', profession: 'Entrepreneur', year_connected: 2021, first_encounter: 'Introduced through a values-based enterprise network in Sydney.', resonated_quality: 'Accountability', life_changes: 'Shifted business priorities toward ethical growth and service.', continuing_engagement: 'Supporting entrepreneurship and mentorship initiatives in Sydney.' },
    { id: 'd046', full_name: 'Dr. Ethan Clarke', country: 'Australia, Melbourne', profession: 'Doctor', year_connected: 2022, first_encounter: 'Connected through a health and resilience dialogue in Melbourne.', resonated_quality: 'Compassion', life_changes: 'Integrated deeper empathy and reflection into clinical practice.', continuing_engagement: 'Participating in health education and healing-oriented initiatives in Melbourne.' },
  
    { id: 'd047', full_name: 'Dr. Maia Thompson', country: 'New Zealand, Auckland', profession: 'Researcher', year_connected: 2023, first_encounter: 'Introduced through a research and ethics network in Auckland.', resonated_quality: 'Clarity', life_changes: 'Developed a more integrated and values-based approach to inquiry.', continuing_engagement: 'Contributing to research dialogue and educational initiatives in Auckland.' },
  ];

  export const dummyMembersFour = [
    { id: 'd021', full_name: 'Sarah Johnson', country: 'United States, New York City', profession: 'Banker', year_connected: 2020, city : ""   },
    { id: 'd030', full_name: 'Amb. Aisha Rahman', country: 'United Kingdom, London', profession: 'Diplomat', year_connected: 2021, city : ""},
    { id: 'd014', full_name: 'Prof. Nusrat Jahan', country: 'Bangladesh, Sylhet', profession: 'Professor', year_connected: 2020,  },
    { id: 'd040', full_name: 'Dr. Lina Andersson', country: 'Sweden, Stockholm', profession: 'Environmental Scientist', year_connected: 2022,city : ""},
  ];